# Generated by Django 6.1 on 2026-08-20 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('years_active', models.PositiveIntegerField(default=0)),
                ('story', models.TextField()),
                ('quote', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miner Profile',
                'verbose_name_plural': 'Miner Profiles',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MiningStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('equipment', models.TextField(blank=True)),
                ('safety_info', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mining Stage',
                'verbose_name_plural': 'Mining Stages',
                'ordering': ['display_order'],
            },
        ),
    ]
