# Generated by Django 6.1 on 2026-08-14 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('Tourism', 'Tourism'), ('Heritage', 'Heritage'), ('Mining', 'Mining'), ('Adventure', 'Adventure'), ('Culture', 'Culture'), ('Community', 'Community'), ('Nature', 'Nature')], max_length=30)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=6)),
                ('max_capacity', models.PositiveIntegerField(default=20)),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('registration_deadline', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FULL', 'Full'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
