# Generated by Django 6.1 on 2026-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('hero_eyebrow', models.CharField(default='Kenya · Community-led travel', max_length=100)),
                ('hero_heading', models.CharField(default="Discover Kenya's Hidden Heritage", max_length=200)),
                ('hero_subtitle', models.TextField(default='Experience unforgettable journeys through history, culture, wildlife, artisanal mining, breathtaking landscapes and authentic community stories.')),
                ('hero_image', models.URLField(blank=True, null=True)),
                ('hero_video', models.URLField(blank=True, null=True)),
                ('primary_cta_text', models.CharField(default='Explore Tourism', max_length=60)),
                ('primary_cta_url', models.CharField(default='/tourism', max_length=200)),
                ('secondary_cta_text', models.CharField(default='Explore Mining', max_length=60)),
                ('secondary_cta_url', models.CharField(default='/mining', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage content',
                'verbose_name_plural': 'Homepage content',
            },
        ),
    ]
