# Generated by Django 6.1 on 2026-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='about_blocks',
            field=models.JSONField(blank=True, default=list, help_text='List of {"heading": "...", "paragraph": "..."} content blocks.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_description',
            field=models.TextField(default="Pawmula Ltd was founded to open Kenya's hidden heritage to the world."),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_eyebrow',
            field=models.CharField(default='About Pawmula', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_title',
            field=models.CharField(default='Heritage told by the people who live it', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='community_stats',
            field=models.JSONField(blank=True, default=list, help_text='List of {"label": "...", "value": N} stat objects.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_subtitle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_title',
            field=models.CharField(default="Your journey into Kenya's heritage starts here", max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='featured_destination_slugs',
            field=models.JSONField(blank=True, default=list, help_text='List of destination slugs to feature on the homepage.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='trust_badges',
            field=models.JSONField(blank=True, default=list, help_text='List of {"icon": "...", "title": "...", "text": "..."} objects.'),
        ),
    ]
