# Generated by Django 6.1 on 2026-08-14 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('Tourism', 'Tourism'), ('Mining', 'Mining'), ('Heritage', 'Heritage'), ('Events', 'Events'), ('Community', 'Community'), ('Nature', 'Nature'), ('Culture', 'Culture')], max_length=30)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
