# Generated by Django 6.1 on 2026-08-14 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('Tourism', 'Tourism'), ('Heritage', 'Heritage'), ('Mining', 'Mining'), ('Adventure', 'Adventure'), ('Culture', 'Culture'), ('Community', 'Community'), ('Nature', 'Nature')], max_length=30)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=6)),
                ('max_guests', models.PositiveIntegerField(default=10)),
                ('images', models.JSONField(blank=True, default=list)),
                ('video', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='destinations.destination')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
