# Generated by Django 6.1 on 2026-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='PAWMULA.LTD', max_length=200)),
                ('tagline', models.CharField(default='HERITAGE . KENYA', max_length=200)),
                ('address', models.CharField(default='Migori County, Kenya', max_length=300)),
                ('phone_numbers', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(default='pawmulamigori@gmail.com', max_length=254)),
                ('whatsapp_url', models.URLField(blank=True, default='https://wa.me/254702275883')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('footer_description', models.TextField(default='Heritage tourism, artisanal gold mining experiences and community-led journeys across western Kenya.')),
                ('newsletter_text', models.CharField(default='Stories from the field, twice a month.', max_length=200)),
                ('map_embed_url', models.URLField(blank=True, default='')),
                ('map_lat', models.DecimalField(decimal_places=6, default=-0.0917, max_digits=9)),
                ('map_lng', models.DecimalField(decimal_places=6, default=34.768, max_digits=9)),
                ('seo_title', models.CharField(default="Pawmula Ltd -- Discover Kenya's Hidden Heritage", max_length=255)),
                ('seo_description', models.TextField(default="Explore Kenya's hidden heritage through community-led tourism, artisanal gold mining experiences and authentic cultural journeys in Migori and Kisumu counties.")),
                ('seo_og_image', models.URLField(blank=True, null=True)),
                ('seo_author', models.CharField(default='Pawmula Ltd', max_length=150)),
                ('default_currency', models.CharField(default='KES', max_length=6)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
